@host = https://app-sales-eastus2-a9a4ggbxd4gucze8.eastus2-01.azurewebsites.net/

### Get all sales
GET {{host}}/sales
Accept: application/json

### Get sales within a specific date range
GET {{host}}/sales?startDate=2025-03-12&endDate=2025-03-12
Accept: application/json

### Get OPENAPI schema
GET {{host}}/openapi/v1.json
Accept: application/json